modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="create_ticket"
version="0.1.1"
displayName="create train ticket"
credits="Make with mcreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Azur84"

[[dependencies.create_ticket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.create_ticket]]
    modId="create"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_ticket]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

